# Generated by Django 5.2.11 on 2026-03-31 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('risk_score', models.FloatField()),
                ('rule_triggered', models.CharField(blank=True, default='', max_length=255)),
                ('ml_triggered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensorreading')),
            ],
            options={
                'db_table': 'hazard_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
