# Generated by Django 5.2.11 on 2026-03-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gas_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('smoke_level', models.FloatField()),
                ('location', models.CharField(max_length=80)),
                ('shift', models.CharField(max_length=20)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('synthetic', 'Synthetic'), ('csv', 'CSV')], default='manual', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('alarm', models.BooleanField(blank=True, null=True)),
                ('predicted_risk_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]

